still about parsing xml
NY Phil updated a xml file for their complete performing history. I don't need to merge datasets if I'm using it, but when I run the code, it keeps on giving me an error, and I don't know how to fix it. I looked up, but didn't find any R solutions. 

Opening and ending tag mismatch: movement line 917311 and em
Opening and ending tag mismatch: work line 917308 and movement
Opening and ending tag mismatch: worksInfo line 917264 and work
Opening and ending tag mismatch: program line 917252 and worksInfo
Opening and ending tag mismatch: programs line 3 and program
Extra content at the end of the document
Error: 1: Opening and ending tag mismatch: movement line 917311 and em
2: Opening and ending tag mismatch: work line 917308 and movement
3: Opening and ending tag mismatch: worksInfo line 917264 and work
4: Opening and ending tag mismatch: program line 917252 and worksInfo
5: Opening and ending tag mismatch: programs line 3 and program
6: Extra content at the end of the docum